import type { ProjectThumb } from "./interfaces";

export const projects: ProjectThumb[] = [
  {
    photo: "/project/favoritegallery/cover.png",
    name: "Favorites",
    link: "/project/favoritegallery",
    type: "website",
    time: "Feb 2025",
    lang: ["angular", "dummyjson"],
  },
  {
    photo: "/project/7echno/cover.jpg",
    name: "7echno",
    link: "/project/7echno",
    type: "webapp",
    time: "Oct 2023",
    lang: ["svelte", "firebase"],
  },
  {
    photo: "/project/monitoring/cover.jpg",
    name: "EVA - Monitoring",
    link: "/project/monitoring",
    type: "webapp",
    time: "Dec 2022",
    lang: ["angular", "material", "aws"],
  },
  {
    photo: "/project/heatmap/cover.jpg",
    name: "EVA - Heatmap",
    link: "/project/heatmap",
    type: "design",
    time: "Sept 2022",
    lang: ["figma"],
  },
  {
    photo: "/project/network/_cover.png",
    name: "Yukka - Network",
    link: "/project/network",
    type: "webapp",
    time: "Jan 2018",
    lang: ["angular", "d3"],
  },
  {
    photo: "/project/chartmap/_cover.jpg",
    name: "Yukka - Chartmap",
    link: "/project/chartmap",
    type: "webapp",
    time: "Jul 2018",
    lang: ["angular", "highchart"],
  },
  {
    photo: "/gallery/gameapp.jpg",
    name: "Game App",
    link: "/project/gameapp",
    type: "webapp",
    time: "Sep 2022",
    lang: ["svelte"],
  },
  {
    photo: "/project/doinstruct/cover.webp",
    name: "Doinstruct",
    link: "/project/doinstruct",
    type: "webapp",
    time: "Oct 2024",
    lang: ["Svelte", "API"],
  },
  {
    photo: "/project/berlinticket/berlinticket0.jpg",
    name: "Ticket",
    link: "/project/berlinticket",
    type: "webapp",
    time: "Jul 2022",
    lang: ["angular", "material", "firebase"],
  },
  {
    photo: "/project/sentiment/_cover.jpg",
    name: "Yukka - Sentiment",
    link: "/project/sentiment",
    type: "webapp",
    time: "April 2014",
    lang: ["angular", "highchart"],
  },
  {
    photo: "/project/linus-marketing/_cover.jpeg",
    name: "Linus - Marketing",
    link: "/project/linus-marketing",
    type: "website",
    time: "Feb 2022",
    lang: ["react", "builder"],
  },
  {
    photo: "/project/linus-product/_cover.jpeg",
    name: "Linus - Product",
    link: "/project/linus-product",
    type: "website",
    time: "Sep 2021",
    lang: ["react", "builder"],
  },
  {
    photo: "/project/linus-registration/_cover.jpeg",
    name: "Linus - Registration",
    link: "/project/linus-registration",
    type: "webapp",
    time: "Apr 2021",
    lang: ["angular", "material"],
  },
  {
    photo: "/project/uicomponents/_cover.jpeg",
    name: "Building - Components",
    link: "/project/uicomponents",
    type: "webapp",
    time: "Jan 2020",
    lang: ["augular"],
  },
  {
    photo: "/project/appmanager/_cover.jpeg",
    name: "Building - Appmanager",
    link: "/project/appmanager",
    type: "webapp",
    time: "May 2021",
    lang: ["angular"],
  },
  {
    photo: "/project/serenitas/serenitas-00.jpg",
    name: "Serenitas",
    link: "/project/serenitas",
    type: "design",
    time: "Jan 2015",
    lang: ["illustrator"],
  },
  {
    photo: "/project/7echno-logo/logo1.png",
    name: "7echno",
    link: "/project/7echno-logo",
    type: "design",
    time: "Dec 2023",
    lang: ["figma"],
  },
  {
    photo: "/project/firenze/_cover.png",
    name: "Firenze",
    link: "/project/firenze",
    type: "design",
    time: "Aug 2012",
    lang: ["illiustrator"],
  },
  {
    photo: "/project/mklogo/marcellokabora.jpg",
    name: "Marcello Kabora",
    link: "/project/mklogo",
    type: "design",
    time: "Apr 2013",
    lang: ["illustrator"],
  },
  {
    photo: "/project/loretdemar/loretdemar-00.png",
    name: "Tanglang - Lloret De Mar",
    link: "/project/loretdemar",
    type: "website",
    time: "Mar 2015",
    lang: ["Jquery"],
  },
  {
    photo: "/project/wokamoka-avatar/wokamoka-avatar-00.jpg",
    name: "Wokamoka",
    link: "/project/wokamoka-avatar",
    type: "design",
    time: "Jun 2010",
    lang: ["illustrator"],
  },
  {
    photo: "/project/wokamoka-website/wokamoka-website-00.png",
    name: "Wokamoka",
    link: "/project/wokamoka-website",
    type: "website",
    time: "Oct 2010",
    lang: ["flash"],
  },
  {
    photo: "/project/mineko-upload/_cover.jpg",
    name: "Uploader",
    link: "/project/mineko-upload",
    type: "webapp",
    time: "Mar 2017",
    lang: ["augular", "material", "firebase"],
  },
  {
    photo: "/project/airesis/airesis-00.png",
    name: "Airesis",
    link: "/project/airesis",
    type: "webapp",
    time: "Dec 2014",
    lang: ["jquery"],
  },
  {
    photo: "/project/iaa/iaa_00.png",
    name: "Tanglang - IAA",
    link: "/project/iaa",
    type: "website",
    time: "Feb 2015",
    lang: ["jquery"],
  },
  {
    photo: "/project/signals/_cover.jpg",
    name: "Yukka - Signals",
    link: "/project/signals",
    type: "webapp",
    time: "Feb 2018",
    lang: ["angular", "highchart"],
  },
  {
    photo: "/project/autoginevra/autoginevra_00.png",
    name: "Tanglang - Autoginevra",
    link: "/project/autoginevra",
    type: "website",
    time: "Jul 2015",
    lang: ["jquery"],
  },
  {
    photo: "/project/maggiolino/maggiolino_00.png",
    name: "Maggiolino",
    link: "/project/maggiolino",
    type: "website",
    time: "Mar 2015",
    lang: ["jquery", "bootstrap"],
  },
  {
    photo: "/project/smava-website/smava_website_00.jpg",
    name: "Smava - Website",
    link: "/project/smava-website",
    type: "website",
    time: "Jun 2016",
    lang: ["backbone", "semantic"],
  },
  {
    photo: "/project/yawiki/_cover.png",
    name: "Yawiki",
    link: "/project/yawiki",
    type: "webapp",
    time: "Oct 2015",
    lang: ["jquery"],
  },
  {
    photo: "/project/cosmoprof/cosmoprof_00.png",
    name: "Tanglang - Cosmoprof",
    link: "/project/cosmoprof",
    type: "website",
    time: "Apr 2014",
    lang: ["jquery"],
  },
  {
    photo: "/project/christmas/christmas_00.png",
    name: "Tanglang - Christmas",
    link: "/project/christmas",
    type: "website",
    time: "Mar 2014",
    lang: ["jquery"],
  },
  {
    photo: "/project/mineko-website/_cover.png",
    name: "Mineko",
    link: "/project/mineko-website",
    type: "website",
    time: "Jan 2017",
    lang: ["react"],
  },
  {
    photo: "/project/nbe/nbe-00.jpg",
    name: "NBE",
    link: "/project/nbe",
    type: "design",
    time: "Feb 2012",
    lang: [],
  },
  {
    photo: "/project/smava-recommendation/image1.jpg",
    name: "Smava - Recommendation",
    link: "/project/smava-recommendation",
    type: "recommendation",
    time: "Nov 2016",
    lang: [],
  },
];
